### ISSUE TITLE
Had to comment out ip check to make cache_pbs_data() work (utils.R)

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfplot#29]
For SQL server accounts only..
Not entirely sure why, but possibly due to the hardwired 0.5 timeout in `is_ip_valid()`.
I commented out:
```
 if (!sql_server_accessible()) {
    stop("SQL server not accessible.")
  }
```
in `db_connection` and it worked.

**Comment by seananderson** [comment]
Can you experiment with `is_ip_valid()`? Maybe try changing the timeout?

```r
is_ip_valid <- function(ip = "199.60.94.30") {
  out <- pingr::ping(ip, verbose = FALSE,
    count = 1L, timeout = 0.5)
  !is.na(out)
}
```

**Comment by cgrandin** [comment]
I thought about it, but it works as-is for the individual get_* commands and only fails for the `cache_pbs_data()` call and it takes awhile. I'd like to put this on the backburner until I can get the PCod data done..

**Comment by seananderson** [comment]
Weird. Must be something like the timeout since that seems random. I'll test and fix once I get IP access. (The default is now 1 second.)

Yes, focus on the p cod data and let me know if you want me to bite off some of it.

**Comment by cgrandin** [comment]
I see you changed it to 1, and this time it worked (after fixing minor bug). So probably an anomaly with the timeout being too long earlier.
