### ISSUE TITLE
All data extraction fails

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfplot#30]
At commit 61f814d4877b9e58bc8545168eb4f3910fdf170e, and now I cannot extract any data. All calls to `get_*()` and `cache_pbs_data()` just go forever without data being extracted.

I'm thinking you need to try it while here, but I don't see any bugs anywhere.

**Comment by seananderson** [comment]
Shoot, just fixed it I think:
https://github.com/pbs-assess/gfplot/commit/66a82f289c6b2c8a48d18a79889e987500c01e53

And you do have `pbs.ip` set in your options, right?

**Comment by cgrandin** [comment]
Yea I have it set.. That's hard to spot, just an !!!
