### ISSUE TITLE
One of the examples is not working (for me)

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfplot#34]
I've got each example working, except for:

    > get_cpue_index(gear = "bottom trawl", min_cpue_year = 2012)
    Error in `$<-.data.frame`(`*tmp*`, SPECIES_COMMON_NAME, value = character(0)) : 
      replacement has 0 rows, data has 705209

I've looked at the function but can't see any issue. [Sean - my username was just wrong in the server's permissions, so Maria fixed it].

**Comment by seananderson** [comment]
Does `get_cpue_index(gear = "bottom trawl", min_cpue_year = 2016)` work? Min year might have to be greater than 1996.

**Comment by andrew-edwards** [comment]
No, doesn't work (the 2012 is still >1996). I also tried no year argument, and 1996 and 1995 (which I expected shouldn't work). The help says 1996 onward.

I wondered if it was a permission issue with the `GFFOS.GF_MERGED_CATCH`, but
     get_catch("lingcod")
example works and also uses `GFFOS.GF_MERGED_CATCH'.

**Comment by elisekeppel** [comment]
fixed in commit a1e84f3

**Comment by andrew-edwards** [comment]
We all fixed it! Efficiency at work.

I just did it because Elise couldn't push, and to demonstrate what happens when we both do the same edit and don't get a conflict. 
Note that her commit had a bunch of other stuff that got reverted, which I presume was intentional.
I'm off this afternoon so will have to try the big data pull another time.
