### ISSUE TITLE
Add .dll files to .Rbuildignore?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfplot#42]
Presumably they should. I get a warning when running `check()`:
```
* checking for executable files ... WARNING
Found the following executable files:
  inst/tmb/delta_gamma_cpue.dll
  inst/tmb/deltalognormal.dll
Source packages should not contain undeclared executable files.
```

I can do it, just wanted to check.

**Comment by seananderson** [comment]
Sure, add them. Technically it's not needed because they are not in the source of the package -- they are just there because at some point they got built when you ran one of the models. But it doesn't hurt to ignore them to reduce the spurious warnings on your local build.

**Comment by andrew-edwards** [comment]
Thanks. And Travis doesn't care because he doesn't have them.
