### ISSUE TITLE
Think we can fix Travis?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfplot#43]
I know you've tried a bunch of options. I'll start moving more functions into gfplot and want to check I'm not breaking anything. It worked so well before.

**Comment by seananderson** [comment]
Tried a bunch of things and gave up. I’m sure there will be a solution soon or it will just start working. Just do local devtools::check runs for now.

**Comment by andrew-edwards** [comment]
Yes, I'll keep doing check(). Hopefully Travis will start again automatically.
