### ISSUE TITLE
Sean to fetch new branch (but not quite yet)

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfplot#50]
I created a new branch   `merge-from-master` by the following:
```
git co master
git cb merge-from-master
git merge iphc-funcs   [my development branch, but I'd been merging master into it frequently]
```

So rather than pull all my changes into `master`, it seems safer if Sean fetches my merge-from-master branch and check the package builds okay. It should (gfsynopsis will have some conflicts I expect - I'll fix them before doing the same thing).

Maybe hold off until I do the same for gfsynopsis and then I try and rebuild all the figures with the `merge-from-master` version of each repo. If anything breaks I should be able to fix.

**Comment by andrew-edwards** [comment]
Ignore the branch `test-merge` - I created that inadvertently.
The Network Graph seems to be slow in updating tonight (not helping my verification of branches!).

**Comment by seananderson** [comment]
All merged
