### ISSUE TITLE
get_catch SQL error

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfplot#58]
get_catch seems to be broken by these recent commits for many species that are not hake: https://github.com/pbs-assess/gfplot/commit/b5cd452ce44cb4b23b745202130040675c345261  https://github.com/pbs-assess/gfplot/commit/2773cca43abe546b4997e95a98b3926f14ccef02

I get a SQL error. E.g.

```r
get_catch("pacific hake")
```
works

```r
get_catch("pacific cod")
```

does not.

It works if I revert these 2 commits. @cgrandin or @elisekeppel , can you see why?

**Comment by seananderson** [comment]
P.S. on the topic of discovering when we break things, I updated the unit tests so that they will work with username/password access. They exercise most of the get-data functions (although I've currently commented out the catch one). The only trick is that you need to call devtools::test() from the console, not from the RStudio menu, so that it accesses your .Rprofile options.

**Comment by elisekeppel** [comment]
Looks like a field type error due to funny field names from Sablefish fishery (must not be any hake caught in that fishery). But those changes also appear to return more lines – possibly due to multiple trip types on some trips. I’ll check.

Will the way we eliminate duplicates in tidy/plot functions in the R code in get-catch deal with that?

**Comment by elisekeppel** [comment]
The duplication of trip id's gets pretty mixed up in the multiple trip types. 

I think that we should stick with the pre-hake-altered query, and if this is a requirement for many species, revisit at that point. Hake numbers aren't duplicated, so it's fine to use the altered query for just that species but not safe for others.

**Comment by seananderson** [comment]
That sounds like a plan. So hake should have its own SQL. It could either be in this package with an argument in get_catch that controls whether it gets called in place of the usual SQL or could be pulled out into the hake repository. I'm fine with either.

**Comment by seananderson** [comment]
OK, I created `get_hake_catch()` and restored the previous version of `get_catch()`. @cgrandin you will want your scripts to call `get_hake_catch()`.
