### ISSUE TITLE
Make as many of the IPHC functions as possible internal rather than exported

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfplot#59]
I assume only 2 or 3 need to be exposed to the user

**Comment by seananderson** [comment]
After looking at how extensive the IPHC functions are, I decided to move them into their own package:
https://github.com/pbs-assess/gfiphc

This will make it easier to maintain and test the gfplot package (and the IPHC functions). It will also make for fewer functions for a new user to wade through if they do not need the IPHC functionality. Conversely, it will make it easier to focus on the IPHC functionality if the user needs that.

**Comment by andrew-edwards** [comment]
Sounds good - sorry for not having time to get to this...
